.PHONY: clean All

All:
	@echo "----------Building project:[ AMAZON - Debug ]----------"
	@cd "AMAZON" && "$(MAKE)" -f  "AMAZON.mk"
clean:
	@echo "----------Cleaning project:[ AMAZON - Debug ]----------"
	@cd "AMAZON" && "$(MAKE)" -f  "AMAZON.mk" clean
